version: "3"
services:
  golang:
    build:
      context: ./conf/golang
      args:
        GOLANG_SRC_DIR: ${GOLANG_SRC_DIR}
        GOLANG_SRC_DIR_NAME: ${GOLANG_SRC_DIR_NAME}
    volumes:
      - ${GOLANG_SRC_DIR}:/go/src/:rw
    ports:
      - "${GOLANG_HOST_PORT}:8088"
    networks:
      - default
    tty: true

  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "${PHPMYADMIN_HOST_PORT}:80"
    networks:
      - default
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306

networks:
  default: